from typing import Any, Awaitable, Callable, Literal

class Signal:
    def __init__(self, name: str | None = None) -> None: ...
    def connect(
        self, callback: Callable[..., Any], weak: bool = False, priority: int = 0
    ) -> int: ...
    def connect_once(
        self, callback: Callable[..., Any], weak: bool = False, priority: int = 0
    ) -> int: ...
    def connect_finite(
        self,
        callback: Callable[..., Any],
        times: int,
        weak: bool = False,
        priority: int = 0,
    ) -> int: ...
    def disconnect(self, id: int) -> bool: ...
    def connected(
        self, callback: Callable[..., Any], weak: bool = False, priority: int = 0
    ) -> SignalConnection: ...
    def emit(
        self,
        *args: Any,
        on_error: Literal["fast_fail", "collect"] = "fast_fail",
        **kwargs: Any,
    ) -> list[Any]: ...
    def emit_async(self, *args: Any, **kwargs: Any) -> Awaitable[list[Any]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class SignalConnection:
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...
